# Generated by Django 5.1.1 on 2024-09-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_speaker_user_created_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAllowerSpeaker',
            new_name='UserAllowedSpeaker',
        ),
    ]
