# Generated by Django 5.1.1 on 2024-09-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userallowerspeaker_userallowedspeaker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAllowedSpeaker',
            new_name='AllowedSpeaker',
        ),
    ]
