# Generated by Django 5.1.1 on 2024-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_userallowedspeaker_allowedspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='speaker_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
