# Generated by Django 5.1.1 on 2024-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vowel_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='vowel',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
