# Generated by Django 5.1.1 on 2024-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_annotation_vowel_annotation_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vowel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
