# Generated by Django 5.1.1 on 2024-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vowel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vowel',
            name='category_id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
